source 'https://rubygems.org'

gem 'rails', '3.2.22.5'

gem 'bcrypt', '~> 3.1', '>= 3.1.11'
gem 'mysql2'
gem 'sqlite3'
gem 'test-unit', '~> 3.0'
gem 'autoprefixer-rails'
gem 'coffee-rails', '~> 3.2.1'
gem 'sass-rails', '>= 3.2'
gem 'bootstrap-sass', '3.1.1.0'
gem 'uglifier', '>= 1.0.3'
gem 'jquery-rails'
gem 'font-awesome-sass'
gem 'best_in_place'
